CREATE TABLE COMPRA_DET_TMP (
CT_FOLIO TINYINT NOT NULL,
CT_SERIE CHAR(3) NOT NULL,
CT_ID_TIPODOCTO TINYINT NOT NULL,
CT_MONTO FLOAT NOT NULL,
CT_ID_PROVEEDOR TINYINT NOT NULL,
CT_ID_ALMACEN TINYINT NOT NULL,
CT_FACTURA VARCHAR(20) NOT NULL,
CT_FECHA DATETIME NOT NULL,
CT_ID_PRODUCTO INT NOT NULL,
CT_CANTIDAD FLOAT NOT NULL,
CT_IMPORTE FLOAT NOT NULL,
CT_IVA FLOAT NOT NULL,
CT_UBICACION TINYINT NOT NULL,
FOREIGN KEY (CT_ID_TIPODOCTO) REFERENCES TIPO_DOCUMENTO(ID_TIPODOCTO),
FOREIGN KEY (CT_ID_PRODUCTO) REFERENCES PRODUCTOS(PR_ID)
);