ALTER FUNCTION FN_REPORTE (@PRODUCTO TINYINT)
RETURNS FLOAT
BEGIN
	DECLARE @REPORTE FLOAT
	SET @REPORTE = ISNULL((SELECT SUM(CD_CANTIDAD) FROM COMPRAS_DETALLE WHERE CD_ID_PRODUCTO=@PRODUCTO) - (SELECT SUM(VD_CANTIDAD) FROM VENTAS_DETALLE WHERE VD_ID_PRODUCTO=@PRODUCTO),0)

	RETURN @REPORTE
END
--SELECT dbo.FN_IMP_PEDIDOS(5)

--SELECT ((SELECT SUM(CD_CANTIDAD) FROM COMPRAS_DETALLE WHERE CD_ID_PRODUCTO=2) - (SELECT SUM(VD_CANTIDAD) FROM VENTAS_DETALLE WHERE VD_ID_PRODUCTO=2))