ALTER PROCEDURE SP_COMPRAS_DETALLES
@OP TINYINT = 0,
@CD_FOLIO TINYINT = 0,
@CD_SERIE CHAR(3) = NULL,
@CD_ID_TIPODOCTO TINYINT = 0,
@CD_ID_PRODUCTO INT = 0,
@CD_CANTIDAD FLOAT = 0,
@CD_IMPORTE FLOAT = 0,
@CD_IVA FLOAT = 0,
@CD_UBICACION TINYINT = 0
AS
BEGIN
	--BUSCAR
	IF @OP=1
	BEGIN
		SELECT * from COMPRAS_DETALLE where CD_FOLIO = @CD_FOLIO
	END
	--GUARDA Y ACTUALIZA LOS DATOS DE COMPRA DETALLE---------------------------------------------------------------------------------------------------------------------------------------
	IF @OP = 2
	BEGIN
		IF NOT EXISTS(SELECT * FROM COMPRAS_DETALLE WHERE CD_FOLIO = @CD_FOLIO)
			BEGIN
				INSERT INTO COMPRAS_DETALLE(CD_FOLIO, CD_SERIE, CD_ID_TIPODOCTO, CD_ID_PRODUCTO, CD_CANTIDAD, CD_IMPORTE, CD_IVA, CD_UBICACION)
				SELECT CT_FOLIO, CT_SERIE, CT_ID_TIPODOCTO, CT_ID_PRODUCTO, CT_CANTIDAD, CT_IMPORTE, CT_IVA, CT_UBICACION FROM COMPRA_DET_TMP WHERE CT_FOLIO = @CD_FOLIO
			END
		ELSE
			BEGIN
				DELETE FROM COMPRAS_DETALLE WHERE CD_FOLIO = @CD_FOLIO
				INSERT INTO COMPRAS_DETALLE(CD_FOLIO, CD_SERIE, CD_ID_TIPODOCTO, CD_ID_PRODUCTO, CD_CANTIDAD, CD_IMPORTE, CD_IVA, CD_UBICACION)
				SELECT CT_FOLIO, CT_SERIE, CT_ID_TIPODOCTO, CT_ID_PRODUCTO, CT_CANTIDAD, CT_IMPORTE, CT_IVA, CT_UBICACION FROM COMPRA_DET_TMP WHERE CT_FOLIO = @CD_FOLIO
			END
		--OBTIENE EL CONSECUTIVO DEL ALMACEN
		
	END
	--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	IF @OP = 3
	BEGIN
		DELETE FROM COMPRAS_DETALLE WHERE CD_FOLIO = @CD_FOLIO
	END
END