CREATE PROCEDURE SP_PROVEEDORES
@OP TINYINT = 0,
@PRO_ID TINYINT = 0,
@PRO_NOMBRE VARCHAR(200) = NULL,
@PRO_RFC CHAR(13) = NULL,
@PRO_CORREO VARCHAR(200) = NULL,
@PRO_LADA CHAR(3) = NULL,
@PRO_TELEFONO CHAR(7) = NULL,
@PRO_CALLE VARCHAR(150) = NULL,
@PRO_NUMERO_EXT CHAR(10) = NULL,
@PRO_CTABANCARIA VARCHAR(150) = NULL,
@PRO_CONTACTO VARCHAR(150) = NULL,
@PRO_TELEF_CONTACTO CHAR(10) = NULL,
@PRO_REGIMEN CHAR(3) = NULL
AS
BEGIN
	--BUSCAR
	IF @OP=1
	BEGIN
		SELECT * from PROVEEDORES where PRO_ID = @PRO_ID
	END
	--GUARDA Y ACTUALIZA LOS DATOS DEL PROVEEDOR---------------------------------------------------------------------------------------------------------------------------------------
	IF @OP = 2
	BEGIN
		IF NOT EXISTS(SELECT * FROM PROVEEDORES WHERE PRO_ID = @PRO_ID)
			BEGIN
				--OBTIENE EL CONSECUTIVO DEL PROVEEDOR
				SET @PRO_ID = (SELECT ISNULL(MAX(PRO_ID),0) + 1 FROM PROVEEDORES)
				INSERT INTO PROVEEDORES(PRO_ID, PRO_NOMBRE, PRO_RFC, PRO_CORREO, PRO_LADA, PRO_TELEFONO, PRO_CALLE, PRO_NUMERO_EXT, PRO_CTABANCARIA, PRO_CONTACTO, PRO_TELEF_CONTACTO, PRO_REGIMEN)
				VALUES(@PRO_ID, @PRO_NOMBRE, @PRO_RFC, @PRO_CORREO, @PRO_LADA,@PRO_TELEFONO, @PRO_CALLE, @PRO_NUMERO_EXT, @PRO_CTABANCARIA, @PRO_CONTACTO, @PRO_TELEF_CONTACTO, @PRO_REGIMEN)
			END
		ELSE
			BEGIN
				UPDATE PROVEEDORES SET PRO_NOMBRE = @PRO_NOMBRE, PRO_RFC = @PRO_RFC, PRO_CORREO = @PRO_CORREO, PRO_LADA = @PRO_LADA,
				PRO_TELEFONO = @PRO_TELEFONO, PRO_CALLE = @PRO_CALLE, PRO_NUMERO_EXT = @PRO_NUMERO_EXT, PRO_CTABANCARIA = @PRO_CTABANCARIA,
				PRO_CONTACTO = @PRO_CONTACTO, PRO_TELEF_CONTACTO = @PRO_TELEF_CONTACTO, PRO_REGIMEN = @PRO_REGIMEN
				WHERE PRO_ID = @PRO_ID
			END
	END
	--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	IF @OP = 3
	BEGIN
		DELETE FROM PROVEEDORES WHERE PRO_ID = @PRO_ID
	END
END