ALTER PROCEDURE SP_VENTADETTMP
@OP TINYINT = 0,
@VT_FOLIO TINYINT = 0,
@VT_SERIE CHAR(3) = NULL,
@VT_ID_TIPODOCTO TINYINT = 0,
@VT_MONTO FLOAT = 0,
@VT_ID_CLIENTE TINYINT = 0,
@VT_ID_ALMACEN TINYINT = 0,
@VT_FECHA DATETIME = NULL,
@VT_ID_PRODUCTO INT = 0,
@VT_CANTIDAD FLOAT = 0,
@VT_IMPORTE FLOAT = 0,
@VT_IVA FLOAT = 0
AS
BEGIN
	--BUSCAR
	IF @OP=1
	BEGIN
		SELECT * from VENTA_DET_TMP where VT_FOLIO = @VT_FOLIO
	END
	--GUARDA Y ACTUALIZA LOS DATOS DE LA VENTA---------------------------------------------------------------------------------------------------------------------------------------
	IF @OP = 2
	BEGIN
		INSERT INTO VENTA_DET_TMP(VT_FOLIO, VT_SERIE, VT_ID_TIPODOCTO, VT_MONTO, VT_ID_CLIENTE, VT_ID_ALMACEN, VT_FECHA, VT_ID_PRODUCTO, VT_CANTIDAD, VT_IMPORTE, VT_IVA)
		VALUES(@VT_FOLIO, @VT_SERIE, @VT_ID_TIPODOCTO, @VT_MONTO, @VT_ID_CLIENTE, @VT_ID_ALMACEN, @VT_FECHA, @VT_ID_PRODUCTO, @VT_CANTIDAD, @VT_IMPORTE, @VT_IVA)
	END
	--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	IF @OP = 3
	BEGIN
		DELETE FROM VENTA_DET_TMP WHERE VT_FOLIO = @VT_FOLIO AND VT_ID_PRODUCTO = @VT_ID_PRODUCTO AND VT_CANTIDAD = @VT_CANTIDAD AND VT_IMPORTE = @VT_IMPORTE AND VT_IVA = @VT_IVA
	END
	IF @OP = 4
	BEGIN
		DELETE FROM VENTA_DET_TMP WHERE VT_FOLIO = @VT_FOLIO
	END
END

--SELECT * FROM VENTA_DET_TMP