ALTER PROCEDURE SP_VENTASDETALLES
@OP TINYINT = 0,
@VD_FOLIO TINYINT = 0,
@VD_SERIE CHAR(3) = NULL,
@VD_ID_TIPODOCTO TINYINT = 0,
@VD_ID_PRODUCTO INT = 0,
@VD_CANTIDAD FLOAT = 0,
@VD_IMPORTE FLOAT = 0,
@VD_IVA FLOAT = 0
AS
BEGIN
	--BUSCAR
	IF @OP=1
	BEGIN
		SELECT * from VENTAS_DETALLE where VD_FOLIO = @VD_FOLIO
	END
	--GUARDA Y ACTUALIZA LOS DATOS DE LA VENTA DETALLE---------------------------------------------------------------------------------------------------------------------------------------
	IF @OP = 2
	BEGIN
		IF NOT EXISTS(SELECT * FROM VENTAS_DETALLE WHERE VD_FOLIO = @VD_FOLIO)
			BEGIN
				INSERT INTO VENTAS_DETALLE (VD_FOLIO, VD_SERIE, VD_ID_TIPODOCTO, VD_ID_PRODUCTO, VD_CANTIDAD, VD_IMPORTE, VD_IVA)
				SELECT VT_FOLIO, VT_SERIE, VT_ID_TIPODOCTO, VT_ID_PRODUCTO, VT_CANTIDAD, VT_IMPORTE, 
				VT_IVA FROM VENTA_DET_TMP WHERE VT_FOLIO = @VD_FOLIO
			END
		ELSE
			BEGIN
				DELETE FROM VENTAS_DETALLE WHERE VD_FOLIO = @VD_FOLIO
				INSERT INTO VENTAS_DETALLE (VD_FOLIO, VD_SERIE, VD_ID_TIPODOCTO, VD_ID_PRODUCTO, VD_CANTIDAD, VD_IMPORTE, VD_IVA)
				SELECT VT_FOLIO, VT_SERIE, VT_ID_TIPODOCTO, VT_ID_PRODUCTO, VT_CANTIDAD, VT_IMPORTE, 
				VT_IVA FROM VENTA_DET_TMP WHERE VT_FOLIO = @VD_FOLIO
			END
	END
	--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	IF @OP = 3
	BEGIN
		DELETE FROM VENTAS_DETALLE WHERE VD_FOLIO = @VD_FOLIO
	END
END