CREATE PROCEDURE SP_VENTAS
@OP TINYINT = 0,
@VE_FOLIO TINYINT = 0,
@VE_SERIE CHAR(3) = NULL,
@VE_ID_TIPODOCTO TINYINT = 0,
@VE_MONTO FLOAT = 0,
@VE_ID_CLIENTE TINYINT = 0,
@VE_ID_ALMACEN TINYINT = 0,
@VE_FECHA DATETIME = NULL
AS
BEGIN
	--BUSCAR
	IF @OP=1
	BEGIN
		SELECT * from VENTAS where VE_FOLIO = @VE_FOLIO
	END
	--GUARDA Y ACTUALIZA LOS DATOS DE LA VENTA---------------------------------------------------------------------------------------------------------------------------------------
	IF @OP = 2
	BEGIN
		IF NOT EXISTS(SELECT * FROM VENTAS WHERE VE_FOLIO = @VE_FOLIO)
			BEGIN
				--OBTIENE EL CONSECUTIVO DE LA VENTA
				SET @VE_FOLIO = (SELECT ISNULL(MAX(VE_FOLIO),0) + 1 FROM VENTAS)
				INSERT INTO VENTAS(VE_FOLIO, VE_SERIE, VE_ID_TIPODOCTO, VE_MONTO, VE_ID_CLIENTE, VE_ID_ALMACEN, VE_FECHA)
				VALUES(@VE_FOLIO, @VE_SERIE, @VE_ID_TIPODOCTO, @VE_MONTO, @VE_ID_CLIENTE, @VE_ID_ALMACEN, @VE_FECHA)
			END
		ELSE
			BEGIN
				UPDATE VENTAS SET VE_SERIE = @VE_SERIE, VE_ID_TIPODOCTO = @VE_ID_TIPODOCTO, VE_MONTO = @VE_MONTO,
				VE_ID_CLIENTE = @VE_ID_CLIENTE, VE_ID_ALMACEN = @VE_ID_ALMACEN, VE_FECHA = @VE_FECHA
				WHERE VE_FOLIO = @VE_FOLIO
			END
	END
	--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	IF @OP = 3
	BEGIN
		DELETE FROM VENTAS WHERE VE_FOLIO = @VE_FOLIO
	END
END