CREATE TABLE VENTA_DET_TMP (
VT_FOLIO TINYINT NOT NULL,
VT_SERIE CHAR(3) NOT NULL,
VT_ID_TIPODOCTO TINYINT NOT NULL,
VT_MONTO FLOAT NOT NULL,
VT_ID_CLIENTE TINYINT NOT NULL,
VT_ID_ALMACEN TINYINT NOT NULL,
VT_FECHA DATETIME,
VT_ID_PRODUCTO INT NOT NULL,
VT_CANTIDAD FLOAT NOT NULL,
VT_IMPORTE FLOAT NOT NULL,
VT_IVA FLOAT NOT NULL);